package com.mythara.agent.todo

import android.util.Log
import com.mythara.ai.ModelRouter
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.security.MessageDigest
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Reads the just-written daily-behaviour summary (from
 * [com.mythara.behavior.BehaviorLearningSummarizer]) and any
 * adjacent memory patterns, and asks the LLM to suggest concrete
 * next-action items the agent should run on the user's behalf
 * tomorrow. Writes them into [AgentTodoStore] with
 * [AgentTodoStore.Source.MemoryPattern].
 *
 * This is the second WRITER into the store (the first being
 * [TodoIntentExtractor] for live user-intent capture). Together
 * they keep the [AgentAutoContinueController]'s queue fed without
 * the user having to ask twice.
 *
 * Examples of items this extractor produces:
 *   - Daily summary mentions "missed reminders cluster around
 *     late-evening with reason: tired" → emits item "Suggest moving
 *     evening reminders earlier (8pm → 6:30pm) and confirm with the user."
 *   - Daily summary mentions "skipped morning workout 4 days running" →
 *     emits item "Check in about the morning workout — is the time
 *     wrong, or is something else going on?"
 *
 * Failure modes match [TodoIntentExtractor]:
 *   - Empty summary → no-op.
 *   - Model unavailable → no-op (next daily run gets a fresh shot).
 *   - Non-JSON output → log + no-op.
 *
 * Routing: [ModelRouter.runRaw] with `heavy = false`. Local Gemma is
 * sufficient for "given this 6-bullet summary, what concrete items
 * should the agent take on?" — the daily summary itself was already
 * generated by the heavy path, so the synthesis is condensed. Cost
 * discipline: this runs once per ~6 h via the summariser worker.
 */
@Singleton
class TodoMemoryPatternExtractor @Inject constructor(
    private val router: ModelRouter,
    private val store: AgentTodoStore,
) {
    private val json = Json { ignoreUnknownKeys = true; isLenient = true }

    /**
     * Extract follow-up items from a daily-behaviour summary.
     * Returns the count of items written. Suspending — the
     * BehaviorLearningSummarizer awaits so it can log the count.
     */
    suspend fun extract(daySummaryMd: String, dateLabel: String): Int =
        withContext(Dispatchers.IO) {
            if (daySummaryMd.isBlank()) return@withContext 0
            val prompt = buildPrompt(daySummaryMd, dateLabel)
            val raw = runCatching { router.runRaw(prompt, maxLen = 600, heavy = false) }
                .getOrNull()
                ?.trim()
            if (raw.isNullOrBlank()) {
                Log.d(TAG, "model returned null/blank — no items extracted from $dateLabel summary")
                return@withContext 0
            }
            val items = parseItems(raw)
            if (items.isEmpty()) return@withContext 0

            val now = System.currentTimeMillis()
            var written = 0
            for (text in items) {
                // Stable id keyed by the date so re-running the
                // summariser in the same window doesn't double-add
                // the same suggestions.
                val id = stableId("pattern", dateLabel, text)
                runCatching {
                    store.add(
                        AgentTodoStore.Item(
                            id = id,
                            text = text,
                            source = AgentTodoStore.Source.MemoryPattern,
                            createdAtMs = now,
                        ),
                    )
                    written++
                }.onFailure { Log.w(TAG, "store.add failed: ${it.message}") }
            }
            Log.i(TAG, "extracted $written memory-pattern items from $dateLabel summary")
            written
        }

    private fun buildPrompt(summary: String, date: String): String = buildString {
        append("You are deriving CONCRETE NEXT-ACTION items for a personal-AI assistant ")
        append("from a daily-behaviour summary it just wrote about its user. The summary is ")
        append("the assistant's own observations from the past 24 hours. Date: $date.\n\n")
        append("Your job: read the summary and propose actions the assistant should run on ")
        append("its own initiative tomorrow to actually MOVE THE NEEDLE on the patterns ")
        append("observed. These will be queued and auto-executed during quiet windows.\n\n")
        append("Rules — STRICT:\n")
        append("  1. Output ONLY a JSON array of strings, no preamble, no markdown fences. ")
        append("Empty array [] is valid.\n")
        append("  2. Each string is a single concrete action (max 110 chars), phrased as a ")
        append("verb-leading instruction the agent can execute (\"Ask the user if 6:30pm ")
        append("works better for the evening reminders than 8pm\", not \"User has been ")
        append("missing reminders\").\n")
        append("  3. Items must be GROUNDED in the summary — never invent patterns the ")
        append("summary doesn't describe.\n")
        append("  4. Skip items that are pure observation (\"note that user is tired\") — ")
        append("only emit items that have a concrete tool call or user-visible question.\n")
        append("  5. Cap at 3 items maximum. Pick the highest-leverage ones.\n\n")
        append("--- DAILY SUMMARY ---\n")
        append(summary.take(2000)).append("\n\n")
        append("--- OUTPUT (JSON array of strings only) ---\n")
    }

    private fun parseItems(raw: String): List<String> {
        val cleaned = raw
            .substringAfter("```json", raw)
            .substringAfter("```", raw)
            .substringBefore("```")
            .trim()
            .let { extractFirstArray(it) ?: it }
        val arr: JsonArray = runCatching {
            json.parseToJsonElement(cleaned).jsonArray
        }.getOrElse {
            Log.d(TAG, "parse failed (${it.message}) on: ${cleaned.take(120)}")
            return emptyList()
        }
        return arr.mapNotNull { el ->
            val s = runCatching { el.jsonPrimitive.contentOrNull }.getOrNull()
                ?: runCatching { el.jsonObject["text"]?.jsonPrimitive?.contentOrNull }.getOrNull()
            s?.trim()?.takeIf { it.isNotBlank() && it.length <= 260 }
        }.distinct().take(3)
    }

    private fun extractFirstArray(text: String): String? {
        val start = text.indexOf('[')
        if (start < 0) return null
        var depth = 0
        var i = start
        while (i < text.length) {
            when (text[i]) {
                '[' -> depth++
                ']' -> {
                    depth--
                    if (depth == 0) return text.substring(start, i + 1)
                }
            }
            i++
        }
        return null
    }

    private fun stableId(scope: String, dateLabel: String, text: String): String {
        val md = MessageDigest.getInstance("SHA-256")
        md.update("$scope|$dateLabel|$text".toByteArray())
        return "todo:" + md.digest().take(8).joinToString("") { "%02x".format(it) }
    }

    companion object {
        private const val TAG = "Mythara/TodoPatternExtractor"
    }
}
